name: Java CI

on:
   -push
   -pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.0
        with:
          args: build
